name: Main
on:
- push
- pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@master
      with:
          submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: '3.1'

    - name: Test
      run: |
        bundle exec rake test
        bundle exec rake stree:check
